name: api-e-buteco

services:
  pg:
    image: bitnami/postgresql:17.5.0
    restart: always
    ports:
      - '5532:5532'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db-buteco
    volumes:
      - pgdata:/var/lib/bitnami/postgresql

volumes:
  pgdata:
  

