name: api-e-buteco

services:
  pg:
    image: postgres:17
    restart: always
    ports:
      - '5532:5532'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db-buteco
    volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  

